version: "3"

services:
 # App php-fpm service
 app:
   build:
     context: ./docker/php
     args:
       APP_ENV: ${APP_ENV}
       PHP_VERSION: ${PHP_VERSION}
       REMOTE_WORKING_DIR: ${REMOTE_WORKING_DIR}
   container_name: ${APP_NAME}_app
   restart: unless-stopped
   volumes:
     - ${LOCAL_WORKING_DIR}:${REMOTE_WORKING_DIR}
     - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
   env_file: .env
   ports:
     - 9006:9001
   networks:
     - app-network

 nginx:
   image: nginx:alpine
   container_name: ${APP_NAME}_nginx
   restart: unless-stopped
   volumes:
     - ${LOCAL_WORKING_DIR}:${REMOTE_WORKING_DIR}
     - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
     - ./docker/nginx/ssl/:/etc/nginx/ssl/
   ports:
     - 8189:80
     - 4431:443
   depends_on:
     - app
   networks:
     - app-network

 database:
   image: mysql:5.7
   container_name: ${APP_NAME}_database
   environment:
     MYSQL_DATABASE: ${MYSQL_DATABASE}
     MYSQL_USER: ${MYSQL_USER}
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
   ports:
     - 33062:3306
   volumes:
     - database-volume:/var/lib/mysql
   depends_on:
     - app
   networks:
     - app-network

# Docker Volumes
volumes:
 database-volume:

# Docker Networks
networks:
 app-network:
   driver: bridge